### ISSUE TITLE
hiduino

### ISSUE THREAD

**Issue by Wallirec** [Wang-Derr/ARMIDUINO#1]
Hello, great project!
Tell me, will your sketches work with Hiduino?
I need the sketch to work via USB

**Comment by Wang-Derr** [comment]
Hi @Wallirec I'm not familiar with the Hiduino project, but taking a quick glance at the readme in their Repo I don't see why not as long as you meet their requirements.

It should work, but let me know if it doesn't and I can attempt to test it on my own hardware though that may take some time.

**Comment by Wallirec** [comment]
The numbers on the display change but no messages appear. I don’t have a single encoder, maybe that’s why MIDI messages don’t go through USB.
![photo_5258212071630298414_y](https://github.com/Wang-Derr/ARMIDUINO/assets/76187804/04f05cd5-7bb3-4615-9a1f-51c0c1043b63)

**Comment by Wang-Derr** [comment]
Interesting, how are you changing the numbers without encoders, I'm assuming using that number pad in the photo? The way the code runs is that you need to trigger a button press on _Encoder3_ in order to send the MIDI message, so if you're able to substitute a button press for that, it should work. It's currently mapped to digital pin 13.

**Comment by Wallirec** [comment]
Thank you very much friend! After your hint, everything works - I checked it on the Roland FP-30x (it needs 4 channel, MSB 121, LSB 0 - 1 to access the main 256 sounds of GM2, the rest is garbage).
I connect midi devices to Roland via a USB host, since the piano only has USB type A.
I’ll buy encoders and continue to modify them to suit my needs.
Thanks again for the great sketches!!!
![Good](https://github.com/Wang-Derr/ARMIDUINO/assets/76187804/30603328-901b-4984-bc4c-85b2a84e9960)

**Comment by Wang-Derr** [comment]
Glad it worked out!
