### ISSUE TITLE
Thank you for your hard work!

### ISSUE THREAD

**Issue by Wallirec** [Wang-Derr/ARMIDUINO#3]
Thank you for your hard work! Based on your sketch, I wrote my own, with great difficulty, since I could not find similar information anywhere. After trying several options with the Joystick and encoders, I settled on keyboard input. Since the Roland electric piano has 312 presets, the Arduino Pro Micro was enough for me.
Thank you again, I learned a lot from you (for example, how to use Progmem)!
Now I have access to all 312 presets and a choice of channels and drum sets on the Roland FP 30x (by default, only 57 presets).
![Controller](https://github.com/Wang-Derr/ARMIDUINO/assets/76187804/75448885-64f3-49fe-b74a-4e75b4b65a5f)
![Oled](https://github.com/Wang-Derr/ARMIDUINO/assets/76187804/ec77a8aa-c67e-4549-a272-6ec6218384c7)

**Comment by Wang-Derr** [comment]
That's awesome! Glad that my project helped you along in some way.
